# Generated by Django 3.2.9 on 2021-11-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_project_p_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='emp_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='emp',
            name='emp_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='p_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
